


<!-- LIBS JAVASCRIPT PARA FUNCIONAR BOOTSTRAP E JQUERY, dar include, em todas as paginas que for utilizar ---->

<script src="js/jquery-3.4.1.js"></script>
<script src="js/jquery.blockUI.js"></script>
<script src="js/popper.min.js"></script>
<script src="js/bootstrap.min.js"></script>
<script src="js/bootstrap-datepicker.min.js"></script>
<script src = "js/jquery.growl.js"></script>
<script src="js/locales/bootstrap-datepicker.pt-BR.min.js"></script>
<script src = "js/principal.js"></script>
<script src = "js/matricula.js"></script>
<script src = "js/form_config.js"></script>
<script src="js/configuracoes.js"></script>
<script src="js/jquery.mask.min.js"></script>


